### ISSUE TITLE
How to create two scripts in init.d/

### ISSUE THREAD

**Issue by xieweizhi** [TryGhost/Ghost-Config#34]
I have two ghosts running on the same ubuntu system. I have tried to copy this script to init.d/ with separately. But they can't work at the same time.I need some help, please.

**Comment by ErisDS** [comment]
Hi @xieweizhi sorry to hear you're having trouble. If you need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel (in fact someone was asking a very similar question earlier - not sure if that was you). This is a bug tracker for ongoing development of the Ghost software, and we're not able to do support here!
