### ISSUE TITLE
Use EC2 roles instead of AWS keys

### ISSUE THREAD

**Issue by colin-byrne-1** [TryGhost/Ghost-Config#38]
Hey Ghost members,

I previously set up a ghost blog using AWS IAM access keys, but we have mostly transitioned over to EC2 role based authentication. Is there any way to configure Ghost to use EC2 Roles, so that I can ditch the access keys?

**Comment by aileen** [comment]
Hi @cobyrne09 

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.

**Comment by colin-byrne-1** [comment]
@AileenCGN I have asked in there, but what am I supposed to do if no one's helping?
